name: Latest blog post workflow
on:
    schedule:
        - cron: '0 * * * *'
    workflow_dispatch:
        inputs:
            tags:
                description: 'Tags'
jobs:
    update-readme-with-blog:
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with:
                max_post_count: "4"
                feed_list: https://blog.aaronroh.org/rss,https://dev.to/feed/roharon
